# Generated by Django 5.1.1 on 2024-10-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['added_at'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductApp.offer'),
        ),
    ]
