# Generated by Django 5.1.1 on 2024-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_offer_alter_product_options_product_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added_at'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
