# Generated by Django 5.1.1 on 2024-10-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shopUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='UserApp.shopuser'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='shopUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='UserApp.shopuser'),
        ),
    ]
