# Generated by Django 5.1.1 on 2024-10-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_alter_cart_shopuser_alter_wishlist_shopuser'),
        ('ProductApp', '0003_alter_product_options_alter_product_added_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product')},
        ),
    ]
