# Generated by Django 5.1.1 on 2024-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0003_alter_cartproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(default='lili', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='lili', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashOnDelivery', 'cashOnDelivery'), ('creditCard', 'creditCard')], default='cashOnDelivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
